import { createContext, useContext, useEffect, useMemo, useState } from "react";

const dictionaries = {
  id: {
    navHome: "Beranda", navAbout: "Tentang", navProjects: "Proyek", navEducation: "Pendidikan", navCertificates: "Sertifikat",
    navExperience: "Pengalaman", navServices: "Layanan", navContact: "Kontak", contactMe: "Hubungi saya",
    viewProjects: "Lihat proyek", downloadCv: "Unduh CV", available: "Terbuka untuk peluang",
    loading: "Menyiapkan pengalaman Anda...", retry: "Coba lagi", loadingData: "Memuat konten...",
    errorTitle: "Konten belum dapat dimuat", empty: "Belum ada konten untuk ditampilkan.",
    setupBanner: "Mode penyiapan: tambahkan kredensial Supabase di .env.local untuk memuat dan mengelola konten.",
    projectsTitle: "Proyek pilihan", certificatesTitle: "Sertifikat", experienceTitle: "Pengalaman",
    servicesTitle: "Layanan & harga", contactTitle: "Mari terhubung", search: "Cari...",
    all: "Semua", featured: "Pilihan", visit: "Kunjungi proyek", github: "Lihat kode",
    verify: "Verifikasi", download: "Unduh PDF", send: "Kirim pesan", sending: "Mengirim...",
    name: "Nama", email: "Email", message: "Pesan", messageSent: "Pesan berhasil dikirim. Terima kasih!",
    messageError: "Pesan tidak dapat dikirim. Silakan coba kembali.", readMore: "Selengkapnya",
    contactIntro: "Punya ide atau ingin bekerja sama? Ceritakan kepada saya.",
    phone: "Nomor telepon", contactLocation: "Lokasi", connectOnSocial: "Temukan saya di",
    noResults: "Tidak ada hasil yang cocok.", startingAt: "Mulai dari", unavailable: "Tidak tersedia",
    admin: "Admin", logout: "Keluar", dashboard: "Ringkasan", save: "Simpan", cancel: "Batal",
    delete: "Hapus", edit: "Edit", add: "Tambah", actions: "Aksi", status: "Status", published: "Tayang",
    draft: "Draft", confirmDelete: "Hapus item ini? Tindakan ini tidak dapat dibatalkan.",
    loginTitle: "Masuk ke dashboard", username: "Username", password: "Password", login: "Masuk",
    loginError: "Username atau password tidak valid.", totalProjects: "Total proyek", totalCertificates: "Sertifikat",
    loginRateLimited: "Terlalu banyak percobaan login. Tunggu 15 menit lalu coba lagi.",
    loginNetworkError: "Tidak dapat terhubung ke layanan login. Periksa koneksi dan URL Supabase.",
    loginServiceError: "Layanan login bermasalah. Periksa Edge Function login-username dan konfigurasi Supabase.",
    totalExperience: "Pengalaman", activeServices: "Layanan aktif", unreadMessages: "Pesan belum dibaca",
    profile: "Profil", projects: "Proyek", certificates: "Sertifikat", experiences: "Pengalaman",
    services: "Layanan", skills: "Keahlian", social_links: "Tautan sosial", contact_messages: "Pesan masuk",
    site_settings: "Pengaturan website", media: "Media", title: "Judul", description: "Deskripsi",
    category: "Kategori", sort_order: "Urutan", created_at: "Dibuat", updated_at: "Diperbarui",
    saveSuccess: "Perubahan berhasil disimpan.", genericError: "Terjadi kesalahan. Silakan coba lagi.",
    noMessages: "Belum ada pesan.", latestProjects: "Proyek terbaru", current: "Saat ini",
    full_name: "Nama lengkap", profession: "Profesi", headline: "Headline", bio: "Biografi",
    education: "Pendidikan", location: "Domisili", availability_text: "Teks status ketersediaan",
    section_visibility: "Visibilitas bagian", seo_title: "Judul SEO", seo_description: "Deskripsi SEO",
    slug: "Slug", short_description: "Deskripsi singkat", thumbnail_url: "URL thumbnail",
    gallery_urls: "URL galeri (JSON)", technologies: "Teknologi (JSON)", year: "Tahun",
    github_url: "URL GitHub", live_url: "URL demo", issuer: "Penerbit", issue_date: "Tanggal terbit",
    expiry_date: "Tanggal kedaluwarsa", credential_id: "ID kredensial", verification_url: "URL verifikasi",
    preview_url: "URL preview", pdf_url: "URL PDF", experience_type: "Tipe pengalaman",
    organization: "Perusahaan/organisasi", position: "Posisi", start_date: "Tanggal mulai",
    end_date: "Tanggal selesai", is_current: "Masih berlangsung", responsibilities: "Tanggung jawab (JSON)",
    achievements: "Pencapaian (JSON)", logo_url: "URL logo", price_min: "Harga minimum",
    price_max: "Harga maksimum", price_fixed: "Harga tetap", currency: "Mata uang",
    estimated_duration: "Estimasi durasi", features: "Cakupan/fitur (JSON)", revisions: "Jumlah revisi",
    complexity: "Tingkat kesulitan", field_featured: "Unggulan", field_available: "Tersedia", field_name: "Nama",
    terms: "Syarat dan ketentuan (JSON)", proficiency: "Tingkat keahlian (0-100)",
    platform: "Platform", url: "URL", key: "Kunci pengaturan", value: "Nilai pengaturan (JSON)",
    read_at: "Waktu dibaca", jsonHint: 'Objek terjemahan: {"id":"...","en":"..."}; konten list: ["..."]',
    is_public: "Boleh dibaca publik",
    changeInitialPassword: "Ubah password awal sebelum melanjutkan penggunaan dashboard.",
    minimumPassword: "Minimal 10 karakter", previewUpload: "Pratinjau sebelum upload",
    upload: "Unggah", copyUrl: "Salin URL", invalidUpload: "Pilih gambar JPG, PNG, WebP atau PDF maksimal 10 MB.",
    navDetails: "Navigasi portfolio",
    fileInUse: "File ini masih digunakan oleh konten. Lepaskan file dari konten terlebih dahulu.",
    uploadSuccess: "File berhasil diunggah.",
    errorBoundaryTitle: "Halaman mengalami kendala", reloadPage: "Muat ulang halaman",
    work: "Karya", credentials: "Kredensial", journey: "Perjalanan", freelance: "Jasa lepas",
    sayHello: "Sapa saya", portfolio: "Portofolio", allTechnologies: "Semua teknologi",
    mediaHelp: "Maksimal 10 MB. Foto profil, gambar proyek, dan sertifikat menggunakan bucket publik; dokumen menggunakan penyimpanan privat.",
    profilePlaceholder: "Profil belum diatur. Tambahkan headline melalui dashboard admin.",
    themeLight: "Terang", themeDark: "Gelap", english: "English", indonesian: "Bahasa Indonesia",
    deleteSuccess: "Item berhasil dihapus.", statusUpdated: "Status pesan diperbarui.",
    profilePortrait: "Foto profil", certificatePlaceholder: "Sertifikat", projectPlaceholder: "Proyek",
    imagePreview: "Pratinjau gambar", togglePassword: "Tampilkan atau sembunyikan password",
    closePreview: "Tutup pratinjau", mainNavigation: "Navigasi utama", toggleNavigation: "Buka atau tutup navigasi",
    darkMode: "Gunakan tema gelap", lightMode: "Gunakan tema terang",
    loadMore: "Muat lebih banyak",
    expires: "Kedaluwarsa", credentialId: "ID kredensial", responsibilitiesLabel: "Tanggung jawab",
    complexityLabel: "Tingkat kesulitan", whatsappContact: "Hubungi via WhatsApp",
    revisionCount: "revisi",
    collapseSidebar: "Ciutkan menu", expandSidebar: "Perluas menu",
    educationTitle: "Riwayat pendidikan", learning: "Pembelajaran", currentlyStudying: "Sedang berlangsung",
    finalGrade: "Nilai akhir", technicalSkills: "Keahlian teknis", cvManagement: "Manajemen CV",
    cvSettings: "Pengaturan CV", activeCv: "CV aktif", noCvUploaded: "Belum ada CV yang diunggah.",
    originalFile: "Nama file asli", downloadFilename: "Nama file unduhan", cvButtonEnabled: "Tampilkan tombol Unduh CV",
    cvLabelId: "Label tombol (Bahasa Indonesia)", cvLabelEn: "Label tombol (English)",
    uploadCv: "Unggah CV PDF", replaceCv: "Ganti CV", previewCv: "Pratinjau CV",
    cvUploadLimit: "Pilih file PDF maksimal 5 MB.", uploadingProgress: "Mengunggah CV",
    cvUpdated: "CV berhasil diperbarui.", cvRemoved: "CV dihapus.", oldCvCleanupWarning: "CV baru aktif, tetapi file lama tidak dapat dihapus. Hapus file lama dari bucket jika sudah tidak digunakan.",
    cvUnavailable: "CV belum dapat dimuat.", cvRequired: "Unggah file CV sebelum mengaktifkan tombol.",
    deleteCvConfirm: "Nonaktifkan dan hapus CV ini? Tindakan ini tidak dapat dibatalkan.",
    adminEducation: "Mengelola riwayat pendidikan", adminCv: "Mengelola file CV",
    field_institution: "Institusi", field_degree: "Jenjang pendidikan", field_field_of_study: "Jurusan/program studi",
    field_grade: "IPK/nilai akhir",
    currentlyEnrolled: "Status sedang berlangsung",
    educationVisibility: "Tampilkan bagian pendidikan di website", chooseInstitutionLogo: "Upload/ganti logo institusi",
    skillCategory_Programming: "Pemrograman", skillCategory_Frontend: "Frontend",
    skillCategory_Database: "Database", skillCategory_Backend: "Backend",
    skillCategory_Data: "Data", skillCategory_Tools: "Tools",
    eduInvalidDates: "Tanggal selesai harus sama atau setelah tanggal mulai.",
    eduCurrentEndDate: "Pendidikan yang masih berlangsung tidak boleh memiliki tanggal selesai.",
    required: "Wajib diisi", cvUploadFailed: "CV gagal diunggah. CV aktif sebelumnya tetap tersedia.",
    cvUploadBusy: "Pengunggahan sedang berlangsung.",
    invalidLogo: "Pilih logo JPG, PNG, atau WebP maksimal 5 MB.",
  },
  en: {
    navHome: "Home", navAbout: "About", navProjects: "Projects", navEducation: "Education", navCertificates: "Certificates",
    navExperience: "Experience", navServices: "Services", navContact: "Contact", contactMe: "Contact me",
    viewProjects: "View projects", downloadCv: "Download CV", available: "Open to opportunities",
    loading: "Preparing your experience...", retry: "Try again", loadingData: "Loading content...",
    errorTitle: "Content could not be loaded", empty: "There is no content to display yet.",
    setupBanner: "Setup mode: add Supabase credentials in .env.local to load and manage content.",
    projectsTitle: "Selected projects", certificatesTitle: "Certificates", experienceTitle: "Experience",
    servicesTitle: "Services & pricing", contactTitle: "Let's connect", search: "Search...",
    all: "All", featured: "Featured", visit: "Visit project", github: "View code",
    verify: "Verify", download: "Download PDF", send: "Send message", sending: "Sending...",
    name: "Name", email: "Email", message: "Message", messageSent: "Message sent successfully. Thank you!",
    messageError: "Your message could not be sent. Please try again.", readMore: "Read more",
    contactIntro: "Have an idea or want to collaborate? Tell me about it.",
    phone: "Phone number", contactLocation: "Location", connectOnSocial: "Find me on",
    noResults: "No matching results.", startingAt: "Starting at", unavailable: "Unavailable",
    admin: "Admin", logout: "Sign out", dashboard: "Dashboard", save: "Save", cancel: "Cancel",
    delete: "Delete", edit: "Edit", add: "Add", actions: "Actions", status: "Status", published: "Published",
    draft: "Draft", confirmDelete: "Delete this item? This action cannot be undone.",
    loginTitle: "Sign in to dashboard", username: "Username", password: "Password", login: "Sign in",
    loginError: "Username or password is incorrect.", totalProjects: "Projects", totalCertificates: "Certificates",
    loginRateLimited: "Too many login attempts. Wait 15 minutes and try again.",
    loginNetworkError: "Could not reach the login service. Check your connection and Supabase URL.",
    loginServiceError: "The login service encountered an error. Check the login-username Edge Function and Supabase configuration.",
    totalExperience: "Experience", activeServices: "Active services", unreadMessages: "Unread messages",
    profile: "Profile", projects: "Projects", certificates: "Certificates", experiences: "Experience",
    services: "Services", skills: "Skills", social_links: "Social links", contact_messages: "Messages",
    site_settings: "Website settings", media: "Media", title: "Title", description: "Description",
    category: "Category", sort_order: "Order", created_at: "Created", updated_at: "Updated",
    saveSuccess: "Changes saved.", genericError: "Something went wrong. Please try again.",
    noMessages: "No messages yet.", latestProjects: "Latest projects", current: "Present",
    full_name: "Full name", profession: "Profession", headline: "Headline", bio: "Biography",
    education: "Education", location: "Location", availability_text: "Availability text",
    section_visibility: "Section visibility", seo_title: "SEO title", seo_description: "SEO description",
    slug: "Slug", short_description: "Short description", thumbnail_url: "Thumbnail URL",
    gallery_urls: "Gallery URLs (JSON)", technologies: "Technologies (JSON)", year: "Year",
    github_url: "GitHub URL", live_url: "Live demo URL", issuer: "Issuer", issue_date: "Issue date",
    expiry_date: "Expiry date", credential_id: "Credential ID", verification_url: "Verification URL",
    preview_url: "Preview URL", pdf_url: "PDF URL", experience_type: "Experience type",
    organization: "Company/organization", position: "Position", start_date: "Start date",
    end_date: "End date", is_current: "Currently active", responsibilities: "Responsibilities (JSON)",
    achievements: "Achievements (JSON)", logo_url: "Logo URL", price_min: "Minimum price",
    price_max: "Maximum price", price_fixed: "Fixed price", currency: "Currency",
    estimated_duration: "Estimated duration", features: "Scope/features (JSON)", revisions: "Revision count",
    complexity: "Difficulty", field_featured: "Featured", field_available: "Available", field_name: "Name",
    terms: "Terms and conditions (JSON)", proficiency: "Proficiency (0-100)",
    platform: "Platform", url: "URL", key: "Setting key", value: "Setting value (JSON)",
    read_at: "Read at", jsonHint: 'Translation object: {"id":"...","en":"..."}; list content: ["..."]',
    is_public: "Publicly readable",
    changeInitialPassword: "Change the initial password before continuing to use the dashboard.",
    minimumPassword: "At least 10 characters", previewUpload: "Upload preview",
    upload: "Upload", copyUrl: "Copy URL", invalidUpload: "Choose JPG, PNG, WebP or PDF up to 10 MB.",
    navDetails: "Portfolio navigation",
    fileInUse: "This file is still referenced by content. Remove its content references before deleting it.",
    uploadSuccess: "File uploaded successfully.",
    errorBoundaryTitle: "This page ran into a problem", reloadPage: "Reload page",
    work: "Work", credentials: "Credentials", journey: "Journey", freelance: "Freelance",
    sayHello: "Say hello", portfolio: "Portfolio", allTechnologies: "All technologies",
    mediaHelp: "Maximum 10 MB. Profile, project, and certificate files use public buckets; documents use private storage.",
    profilePlaceholder: "Profile not configured. Add a headline from the admin dashboard.",
    themeLight: "Light", themeDark: "Dark", english: "English", indonesian: "Bahasa Indonesia",
    deleteSuccess: "Item deleted.", statusUpdated: "Message status updated.",
    profilePortrait: "Profile portrait", certificatePlaceholder: "Certificate", projectPlaceholder: "Project",
    imagePreview: "Image preview", togglePassword: "Show or hide password",
    closePreview: "Close preview", mainNavigation: "Main navigation", toggleNavigation: "Toggle navigation",
    darkMode: "Use dark theme", lightMode: "Use light theme",
    loadMore: "Load more",
    expires: "Expires", credentialId: "Credential ID", responsibilitiesLabel: "Responsibilities",
    complexityLabel: "Difficulty", whatsappContact: "Contact via WhatsApp",
    revisionCount: "revisions",
    collapseSidebar: "Collapse sidebar", expandSidebar: "Expand sidebar",
    educationTitle: "Education history", learning: "Learning", currentlyStudying: "Currently studying",
    finalGrade: "Final grade", technicalSkills: "Technical skills", cvManagement: "CV management",
    cvSettings: "CV settings", activeCv: "Active CV", noCvUploaded: "No CV has been uploaded.",
    originalFile: "Original filename", downloadFilename: "Download filename", cvButtonEnabled: "Show Download CV button",
    cvLabelId: "Button label (Bahasa Indonesia)", cvLabelEn: "Button label (English)",
    uploadCv: "Upload CV PDF", replaceCv: "Replace CV", previewCv: "Preview CV",
    cvUploadLimit: "Choose a PDF file up to 5 MB.", uploadingProgress: "Uploading CV",
    cvUpdated: "CV updated successfully.", cvRemoved: "CV removed.", oldCvCleanupWarning: "The new CV is active, but the old file could not be removed. Remove it from the bucket when no longer in use.",
    cvUnavailable: "The CV could not be loaded.", cvRequired: "Upload a CV before enabling its button.",
    deleteCvConfirm: "Disable and delete this CV? This action cannot be undone.",
    adminEducation: "Manage education history", adminCv: "Manage CV file",
    field_institution: "Institution", field_degree: "Degree", field_field_of_study: "Field of study",
    field_grade: "GPA/final grade",
    currentlyEnrolled: "Currently studying",
    educationVisibility: "Show education section on the website", chooseInstitutionLogo: "Upload/replace institution logo",
    skillCategory_Programming: "Programming", skillCategory_Frontend: "Frontend",
    skillCategory_Database: "Database", skillCategory_Backend: "Backend",
    skillCategory_Data: "Data", skillCategory_Tools: "Tools",
    eduInvalidDates: "The end date must be on or after the start date.",
    eduCurrentEndDate: "Current education must not have an end date.",
    required: "Required", cvUploadFailed: "CV upload failed. The previously active CV remains available.",
    cvUploadBusy: "An upload is in progress.",
    invalidLogo: "Choose a JPG, PNG, or WebP logo up to 5 MB.",
  },
};

const PreferencesContext = createContext(null);
export function PreferencesProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("portfolio-language") || "id");
  const [theme, setTheme] = useState(() => {
    const saved = localStorage.getItem("portfolio-theme");
    return saved || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  });
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const changeLanguage = (next) => { localStorage.setItem("portfolio-language", next); setLanguage(next); };
  const changeTheme = (next) => {
    localStorage.setItem("portfolio-theme", next);
    document.documentElement.dataset.theme = next;
    setTheme(next);
  };
  const value = useMemo(() => ({
    language, theme, setLanguage: changeLanguage, setTheme: changeTheme,
    t: (key) => dictionaries[language]?.[key] || dictionaries.id[key] || key,
  }), [language, theme]);
  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}
export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("usePreferences must be used within PreferencesProvider");
  return context;
}
